package com.rrtechnosoft.lms.service.export;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfPageEventHelper;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Generic ".pdf" export used by every report in the Reports & Analytics
 * module, mirroring {@link ExcelExportService}'s contract: hand it a title,
 * headers, and rows, and it lays out a landscape table with a branded header
 * and page numbers. Uses OpenPDF (LGPL/MPL fork of iText 4) rather than
 * iText5+/7 to avoid AGPL licensing on a commercial product.
 */
@Service
public class PdfExportService {

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("dd-MMM-yyyy");
    private static final DateTimeFormatter DATETIME_FMT = DateTimeFormatter.ofPattern("dd-MMM-yyyy HH:mm");
    private static final Color BRAND_RED = new Color(227, 30, 36); // matches frontend brand red (#E31E24)

    public byte[] export(String title, String generatedAtLine, List<String> headers, List<List<Object>> rows) {
        Document document = new Document(PageSize.A4.rotate(), 24, 24, 60, 36);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter writer = PdfWriter.getInstance(document, out);
            writer.setPageEvent(new FooterPageEvent());
            document.open();

            Font titleFont = new Font(Font.HELVETICA, 16, Font.BOLD, BRAND_RED);
            Paragraph titleParagraph = new Paragraph("RR TECHNOSOFT LMS", titleFont);
            titleParagraph.setAlignment(Element.ALIGN_LEFT);
            document.add(titleParagraph);

            Font subtitleFont = new Font(Font.HELVETICA, 13, Font.BOLD, Color.DARK_GRAY);
            document.add(new Paragraph(title, subtitleFont));

            Font metaFont = new Font(Font.HELVETICA, 9, Font.ITALIC, Color.GRAY);
            Paragraph meta = new Paragraph(generatedAtLine, metaFont);
            meta.setSpacingAfter(12);
            document.add(meta);

            if (rows.isEmpty()) {
                document.add(new Paragraph("No records match the selected filters.",
                        new Font(Font.HELVETICA, 10, Font.ITALIC, Color.GRAY)));
            } else {
                document.add(buildTable(headers, rows));
            }

            document.close();
            return out.toByteArray();
        } catch (DocumentException e) {
            throw new UncheckedIOException(new IOException("Failed to generate PDF export", e));
        }
    }

    private PdfPTable buildTable(List<String> headers, List<List<Object>> rows) {
        PdfPTable table = new PdfPTable(headers.size());
        table.setWidthPercentage(100);
        try {
            table.setWidths(evenWidths(headers.size()));
        } catch (DocumentException ignored) {
            // falls back to equal-width columns, which is the PdfPTable default
        }

        Font headerFont = new Font(Font.HELVETICA, 9, Font.BOLD, Color.WHITE);
        for (String h : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(h, headerFont));
            cell.setBackgroundColor(BRAND_RED);
            cell.setPadding(6);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
        }
        table.setHeaderRows(1);

        Font cellFont = new Font(Font.HELVETICA, 8.5f, Font.NORMAL, Color.BLACK);
        boolean shade = false;
        for (List<Object> row : rows) {
            Color bg = shade ? new Color(250, 240, 240) : Color.WHITE;
            for (Object value : row) {
                PdfPCell cell = new PdfPCell(new Phrase(format(value), cellFont));
                cell.setPadding(5);
                cell.setBackgroundColor(bg);
                table.addCell(cell);
            }
            shade = !shade;
        }
        return table;
    }

    private String format(Object value) {
        if (value == null) return "-";
        if (value instanceof LocalDate d) return d.format(DATE_FMT);
        if (value instanceof OffsetDateTime dt) return dt.format(DATETIME_FMT);
        if (value instanceof Double d) return String.format("%,.2f", d);
        return value.toString();
    }

    private float[] evenWidths(int count) {
        float[] widths = new float[count];
        for (int i = 0; i < count; i++) widths[i] = 1f;
        return widths;
    }

    /** Adds "Generated by RR TECHNOSOFT LMS · Page X of Y" to every page's footer. */
    private static class FooterPageEvent extends PdfPageEventHelper {
        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            Font font = new Font(Font.HELVETICA, 8, Font.ITALIC, Color.GRAY);
            Phrase footer = new Phrase("Generated by RR TECHNOSOFT LMS — Page " + writer.getPageNumber(), font);
            com.lowagie.text.pdf.ColumnText.showTextAligned(
                    writer.getDirectContent(), Element.ALIGN_CENTER, footer,
                    document.getPageSize().getWidth() / 2, document.bottomMargin() - 10, 0);
        }
    }
}
