apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rr-lms-prod

resources:
  - ../../base
  - namespace.yaml

patches:
  - target:
      kind: ConfigMap
      name: lms-backend-config
    patch: |-
      - op: replace
        path: /data/CORS_ORIGINS
        value: "https://app.rrtechnosoft.com"
      - op: replace
        path: /data/SEED_DATA
        value: "false"
  - target:
      kind: Ingress
      name: lms-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: app.rrtechnosoft.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: app.rrtechnosoft.com

images:
  - name: docker.io/rrtechnosoft/lms-backend
    newTag: latest
  - name: docker.io/rrtechnosoft/lms-frontend
    newTag: latest
